// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Servis_Centar_Za_Gitare.Data;

#nullable disable

namespace Servis_Centar_Za_Gitare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621204208_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Gitara", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BrojZica")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime>("DatumZaprimanja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("KupacId")
                        .HasColumnType("bigint");

                    b.Property<int>("MarkaId")
                        .HasColumnType("integer");

                    b.Property<string>("SerijskiBroj")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TipGitareId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KupacId");

                    b.HasIndex("MarkaId");

                    b.HasIndex("TipGitareId");

                    b.ToTable("Gitare");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Marke", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Fender"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Gibson"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Yamaha"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Ibanez"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Taylor"
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Martin"
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "PRS"
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "Epiphone"
                        },
                        new
                        {
                            Id = 9,
                            Naziv = "Jackson"
                        },
                        new
                        {
                            Id = 10,
                            Naziv = "Gretsch"
                        },
                        new
                        {
                            Id = 11,
                            Naziv = "ESP"
                        },
                        new
                        {
                            Id = 12,
                            Naziv = "Schecter"
                        },
                        new
                        {
                            Id = 13,
                            Naziv = "Squier"
                        },
                        new
                        {
                            Id = 14,
                            Naziv = "Takamine"
                        },
                        new
                        {
                            Id = 15,
                            Naziv = "Charvel"
                        });
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Nalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumOtvaranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumZatvaranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GitaraId")
                        .HasColumnType("bigint");

                    b.Property<string>("OpisKvara")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("PoslovnicaId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusNalogaId")
                        .HasColumnType("integer");

                    b.Property<long>("StrankaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TehnicarId")
                        .HasColumnType("bigint");

                    b.Property<int>("VrstaPopravkaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GitaraId");

                    b.HasIndex("PoslovnicaId");

                    b.HasIndex("StatusNalogaId");

                    b.HasIndex("StrankaId");

                    b.HasIndex("TehnicarId");

                    b.HasIndex("VrstaPopravkaId");

                    b.ToTable("Nalozi");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.NalogDatoteka", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumUploada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NalogId")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalniNaziv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RelativnaPutanja")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SpremljeniNaziv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TipSadrzaja")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("VelicinaBajtova")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NalogId");

                    b.ToTable("NalogDatoteke");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Poslovnica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Poslovnice");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.StatusNaloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("StatusiNaloga", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Zaprimljen"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "U Obradi"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Čeka Dijelove"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Završen"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Otkazan"
                        });
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Stranka", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DatumRegistracije")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("PoslovnicaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("PoslovnicaId");

                    b.ToTable("Stranke");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.TipGitare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("TipoveGitara", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Aukusticna"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Elektricna"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Klasicna"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "BasGitara"
                        });
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.VrstaPopravka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("VrstePopravke", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Zamjena Žica"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Podešavanje Vrata"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Podešavanje Intonacije"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Zamjena Pragova"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Brušenje Pragova"
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Popravak Elektronike"
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "Zamjena Pickupa"
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "Zamjena Mašinica"
                        },
                        new
                        {
                            Id = 9,
                            Naziv = "Popravak Kobilice"
                        },
                        new
                        {
                            Id = 10,
                            Naziv = "Čišćenje Potenciometara"
                        });
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Zaposlenik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DatumZaposlenja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<double>("Placa")
                        .HasColumnType("double precision");

                    b.Property<long?>("PoslovnicaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TipZaposlenika")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("PoslovnicaId");

                    b.ToTable("Zaposlenici");

                    b.HasDiscriminator<string>("TipZaposlenika").HasValue("Zaposlenik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Znanje", b =>
                {
                    b.Property<long>("TehnicarId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipGitareId")
                        .HasColumnType("integer");

                    b.Property<int>("VrstaPopravkaId")
                        .HasColumnType("integer");

                    b.HasKey("TehnicarId", "TipGitareId", "VrstaPopravkaId");

                    b.HasIndex("TipGitareId");

                    b.HasIndex("VrstaPopravkaId");

                    b.ToTable("Znanja");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.ZapTehnicar", b =>
                {
                    b.HasBaseType("Servis_Centar_Za_Gitare.models.Zaposlenik");

                    b.HasDiscriminator().HasValue("ZapTehnicar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Gitara", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.Stranka", "Kupac")
                        .WithMany("Gitare")
                        .HasForeignKey("KupacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.Marka", "Marka")
                        .WithMany("Gitare")
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.TipGitare", "TipGitare")
                        .WithMany("Gitare")
                        .HasForeignKey("TipGitareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kupac");

                    b.Navigation("Marka");

                    b.Navigation("TipGitare");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Nalog", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.Gitara", "Gitara")
                        .WithMany("Nalozi")
                        .HasForeignKey("GitaraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.Poslovnica", "Poslovnica")
                        .WithMany("Nalozi")
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Servis_Centar_Za_Gitare.models.StatusNaloga", "StatusNaloga")
                        .WithMany("Nalozi")
                        .HasForeignKey("StatusNalogaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.Stranka", "Stranka")
                        .WithMany("Nalozi")
                        .HasForeignKey("StrankaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.ZapTehnicar", "Tehnicar")
                        .WithMany("Nalozi")
                        .HasForeignKey("TehnicarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Servis_Centar_Za_Gitare.models.VrstaPopravka", "VrstaPopravka")
                        .WithMany("Nalozi")
                        .HasForeignKey("VrstaPopravkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gitara");

                    b.Navigation("Poslovnica");

                    b.Navigation("StatusNaloga");

                    b.Navigation("Stranka");

                    b.Navigation("Tehnicar");

                    b.Navigation("VrstaPopravka");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.NalogDatoteka", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.Nalog", "Nalog")
                        .WithMany("Datoteke")
                        .HasForeignKey("NalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nalog");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.RefreshToken", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Stranka", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.AppUser", "AppUser")
                        .WithOne("Stranka")
                        .HasForeignKey("Servis_Centar_Za_Gitare.models.Stranka", "AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Servis_Centar_Za_Gitare.models.Poslovnica", "Poslovnica")
                        .WithMany("Stranke")
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");

                    b.Navigation("Poslovnica");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Zaposlenik", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.Poslovnica", "Poslovnica")
                        .WithMany("Zaposlenici")
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Poslovnica");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Znanje", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.ZapTehnicar", "Tehnicar")
                        .WithMany("Znanja")
                        .HasForeignKey("TehnicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.TipGitare", "TipGitare")
                        .WithMany("Znanja")
                        .HasForeignKey("TipGitareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.VrstaPopravka", "VrstaPopravka")
                        .WithMany("Znanja")
                        .HasForeignKey("VrstaPopravkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tehnicar");

                    b.Navigation("TipGitare");

                    b.Navigation("VrstaPopravka");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Stranka");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Gitara", b =>
                {
                    b.Navigation("Nalozi");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Marka", b =>
                {
                    b.Navigation("Gitare");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Nalog", b =>
                {
                    b.Navigation("Datoteke");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Poslovnica", b =>
                {
                    b.Navigation("Nalozi");

                    b.Navigation("Stranke");

                    b.Navigation("Zaposlenici");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.StatusNaloga", b =>
                {
                    b.Navigation("Nalozi");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Stranka", b =>
                {
                    b.Navigation("Gitare");

                    b.Navigation("Nalozi");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.TipGitare", b =>
                {
                    b.Navigation("Gitare");

                    b.Navigation("Znanja");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.VrstaPopravka", b =>
                {
                    b.Navigation("Nalozi");

                    b.Navigation("Znanja");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.ZapTehnicar", b =>
                {
                    b.Navigation("Nalozi");

                    b.Navigation("Znanja");
                });
#pragma warning restore 612, 618
        }
    }
}
