// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Servis_Centar_Za_Gitare.Data;

#nullable disable

namespace Servis_Centar_Za_Gitare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610120000_AddRepairAttachments")]
    partial class AddRepairAttachments
    {
    }
}
