// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Servis_Centar_Za_Gitare.Data;

#nullable disable

namespace Servis_Centar_Za_Gitare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503222631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Gitara", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BrojZica")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime>("DatumZaprimanja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("KupacId")
                        .HasColumnType("bigint");

                    b.Property<int>("Marka")
                        .HasColumnType("integer");

                    b.Property<string>("SerijskiBroj")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TipGitare")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KupacId");

                    b.ToTable("Gitare");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Nalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumOtvaranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumZatvaranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GitaraId")
                        .HasColumnType("bigint");

                    b.Property<string>("OpisKvara")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("PoslovnicaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("StrankaId")
                        .HasColumnType("bigint");

                    b.Property<long>("TehnicarId")
                        .HasColumnType("bigint");

                    b.Property<int>("VrstaPopravka")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GitaraId");

                    b.HasIndex("PoslovnicaId");

                    b.HasIndex("StrankaId");

                    b.HasIndex("TehnicarId");

                    b.ToTable("Nalozi");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Poslovnica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Poslovnice");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Stranka", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DatumRegistracije")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("PoslovnicaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("PoslovnicaId");

                    b.ToTable("Stranke");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Zaposlenik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DatumZaposlenja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<double>("Placa")
                        .HasColumnType("double precision");

                    b.Property<long?>("PoslovnicaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TipZaposlenika")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("PoslovnicaId");

                    b.ToTable("Zaposlenici");

                    b.HasDiscriminator<string>("TipZaposlenika").HasValue("Zaposlenik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Znanje", b =>
                {
                    b.Property<long>("TehnicarId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipGitare")
                        .HasColumnType("integer");

                    b.Property<int>("VrstaPopravka")
                        .HasColumnType("integer");

                    b.HasKey("TehnicarId", "TipGitare", "VrstaPopravka");

                    b.ToTable("Znanja");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.ZapTehnicar", b =>
                {
                    b.HasBaseType("Servis_Centar_Za_Gitare.models.Zaposlenik");

                    b.HasDiscriminator().HasValue("ZapTehnicar");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Gitara", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.Stranka", "Kupac")
                        .WithMany("Gitare")
                        .HasForeignKey("KupacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kupac");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Nalog", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.Gitara", "Gitara")
                        .WithMany("Nalozi")
                        .HasForeignKey("GitaraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.Poslovnica", "Poslovnica")
                        .WithMany("Nalozi")
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Servis_Centar_Za_Gitare.models.Stranka", "Stranka")
                        .WithMany("Nalozi")
                        .HasForeignKey("StrankaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servis_Centar_Za_Gitare.models.ZapTehnicar", "Tehnicar")
                        .WithMany("Nalozi")
                        .HasForeignKey("TehnicarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gitara");

                    b.Navigation("Poslovnica");

                    b.Navigation("Stranka");

                    b.Navigation("Tehnicar");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Stranka", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.Poslovnica", "Poslovnica")
                        .WithMany("Stranke")
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Poslovnica");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Zaposlenik", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.Poslovnica", "Poslovnica")
                        .WithMany("Zaposlenici")
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Poslovnica");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Znanje", b =>
                {
                    b.HasOne("Servis_Centar_Za_Gitare.models.ZapTehnicar", "Tehnicar")
                        .WithMany("Znanja")
                        .HasForeignKey("TehnicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tehnicar");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Gitara", b =>
                {
                    b.Navigation("Nalozi");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Poslovnica", b =>
                {
                    b.Navigation("Nalozi");

                    b.Navigation("Stranke");

                    b.Navigation("Zaposlenici");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.Stranka", b =>
                {
                    b.Navigation("Gitare");

                    b.Navigation("Nalozi");
                });

            modelBuilder.Entity("Servis_Centar_Za_Gitare.models.ZapTehnicar", b =>
                {
                    b.Navigation("Nalozi");

                    b.Navigation("Znanja");
                });
#pragma warning restore 612, 618
        }
    }
}
